apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-with-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes-with-env
  template:
    metadata:
      labels:
        app: hello-kubernetes-with-env
    spec:
      containers:
      - name: hello-kubernetes-with-env
        image: acrdevcanadacentral.azurecr.io/demo-app:1.0.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: MESSAGE
            value: "Hello from Anirudh via k8s"
