apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    run: nginx
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
